name: Publication Voltixai Live Foot
on:
  schedule:
    # Toutes les 3 minutes
    - cron: '*/3 * * * *'
  # Permet de lancer manuellement pour tester
  workflow_dispatch:

jobs:
  execution:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Lancer le robot
        env:
          ANYSPORT_API_KEY: ${{ secrets.ANYSPORT_API_KEY }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_TOKEN: ${{ secrets.FACEBOOK_TOKEN }}
        run: node index.js
        
